language: node_js
node_js:
  - "12"
install:
## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
## Do similar for other three images
## Tagging
  - docker tag udagram-frontend tanhank2k1/udagram-frontend:lasted
  - docker tag udagram-api-feed tanhank2k1/udagram-api-feed:lasted
  - docker tag udagram-api-user tanhank2k1/udagram-api-user:lasted
  - docker udagram-reverseproxy tanhank2k1/udagram-reverseproxy:lasted

## Push
## Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push tanhank2k1/udagram-frontend:lasted
  - docker push tanhank2k1/udagram-api-feed:lasted
  - docker push tanhank2k1/udagram-api-user:lasted
  - docker push tanhank2k1/udagram-reverseproxy:lasted
## Do similar for other three images